apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: baycddqsl-python 
  janus-idp.io/tekton: baycddqsl-python
  backstage.io/kubernetes-id: baycddqsl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: baycddqsl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml