apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: baycddqsl-python-gitops
  description: This is GitOps manifest for baycddqsl-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=baycddqsl-python
    backstage.io/kubernetes-id: baycddqsl-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: baycddqsl-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:baycddqsl-python
